### ISSUE TITLE
Exception using environment set

### ISSUE THREAD

**Issue by mahileeb** [scalefactory/aws-assume-role#18]
Running 

```aws-assume-role env set -p PROD```

causes

```
error: can't modify frozen String
/opt/rbenv/rbenv-1.1.1/versions/2.4.1/lib/ruby/gems/2.4.0/gems/aws_assume_role-1.0.0/lib/aws_assume_role/cli/actions/set_environment.rb:51:in `block in act_on': can't modify frozen String (RuntimeError)
	from /opt/rbenv/rbenv-1.1.1/versions/2.4.1/lib/ruby/gems/2.4.0/gems/aws_assume_role-1.0.0/lib/aws_assume_role/cli/actions/set_environment.rb:48:in `each'
	from /opt/rbenv/rbenv-1.1.1/versions/2.4.1/lib/ruby/gems/2.4.0/gems/aws_assume_role-1.0.0/lib/aws_assume_role/cli/actions/set_environment.rb:48:in `act_on'
	from /opt/rbenv/rbenv-1.1.1/versions/2.4.1/lib/ruby/gems/2.4.0/gems/aws_assume_role-1.0.0/lib/aws_assume_role/cli/actions/abstract_action.rb:18:in `initialize'
	from /opt/rbenv/rbenv-1.1.1/versions/2.4.1/lib/ruby/gems/2.4.0/gems/aws_assume_role-1.0.0/lib/aws_assume_role/cli/commands/environment.rb:22:in `new'
	from /opt/rbenv/rbenv-1.1.1/versions/2.4.1/lib/ruby/gems/2.4.0/gems/aws_assume_role-1.0.0/lib/aws_assume_role/cli/commands/environment.rb:22:in `block (3 levels) in <module:Cli>'
	from /opt/rbenv/rbenv-1.1.1/versions/2.4.1/lib/ruby/gems/2.4.0/gems/gli-2.17.0/lib/gli/command_support.rb:131:in `execute'
	from /opt/rbenv/rbenv-1.1.1/versions/2.4.1/lib/ruby/gems/2.4.0/gems/gli-2.17.0/lib/gli/app_support.rb:296:in `block in call_command'
	from /opt/rbenv/rbenv-1.1.1/versions/2.4.1/lib/ruby/gems/2.4.0/gems/gli-2.17.0/lib/gli/app_support.rb:309:in `call_command'
	from /opt/rbenv/rbenv-1.1.1/versions/2.4.1/lib/ruby/gems/2.4.0/gems/gli-2.17.0/lib/gli/app_support.rb:83:in `run'
	from /opt/rbenv/rbenv-1.1.1/versions/2.4.1/lib/ruby/gems/2.4.0/gems/aws_assume_role-1.0.0/lib/aws_assume_role/cli.rb:19:in `<module:Cli>'
	from /opt/rbenv/rbenv-1.1.1/versions/2.4.1/lib/ruby/gems/2.4.0/gems/aws_assume_role-1.0.0/lib/aws_assume_role/cli.rb:7:in `<top (required)>'
	from /opt/rbenv/rbenv-1.1.1/versions/2.4.1/lib/ruby/gems/2.4.0/gems/aws_assume_role-1.0.0/bin/aws-assume-role:4:in `require_relative'
	from /opt/rbenv/rbenv-1.1.1/versions/2.4.1/lib/ruby/gems/2.4.0/gems/aws_assume_role-1.0.0/bin/aws-assume-role:4:in `<top (required)>'
	from /opt/rbenv/rbenv-1.1.1/versions/2.4.1/bin/aws-assume-role:22:in `load'
	from /opt/rbenv/rbenv-1.1.1/versions/2.4.1/bin/aws-assume-role:22:in `<main>'
```

**Comment by sftim** [comment]
Thanks for reporting this issue. Can you let us know what gem versions you've seen that with? If you can add the relevant `Gemfile.lock`, that'd be ideal.
